name: Verbesserungsvorschlag
description: Eine neue Funktion oder Verbesserung vorschlagen
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Ausgangsproblem
      description: Welches Problem soll gelöst werden?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Vorschlag
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternativen oder Ergänzungen
